apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: wizbo
  namespace: argocd
spec:
  applicationRefs:
    - namePattern: wizbo
      images:
        - alias: wizbo
          imageName: wizbo