apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wizbo
spec:
  selector:
    matchLabels:
      app: wizbo # has to match .spec.template.metadata.labels
  serviceName: wizbo
  template:
    metadata:
      labels:
        app: wizbo # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: main
        image: kubernetes.default.svc/wizbo
        ports:
        - containerPort: 25565
          name: minecraft
        volumeMounts:
        - name: world
          mountPath: /home/minecraft/server/world
  volumeClaimTemplates:
  - metadata:
      name: world
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "my-storage-class"
      resources:
        requests:
          storage: 1Gi