#apiVersion: bingecraft.net/v0
#kind: BuildStream
#metadata:
#  name: velocity
#  namespace: argocd
#spec:
#  source:
#    repoURL: https://github.com/bingecraft-net/game-plane/images/velocity
#    targetRevision: HEAD
#    docker:
#      context: .
#      file: Containerfile
#      buildArgs:
#        - name: VERSION_VELOCITY
#          value: 3.4.0-SNAPSHOT
#        - name: VERSION_VELOCITY_BUILD
#          value: 558
#
#  imageTags:
#    - 'kubernetes.default.svc/velocity:$git.commit.sha'