apiVersion: apps/v1
kind: Deployment
metadata:
  name: velocity
  labels:
    app: velocity
spec:
  selector:
    matchLabels:
      app: velocity
  template:
    metadata:
      labels:
        app: velocity
    spec:
      containers:
      - name: velocity
        image: kubernetes.default.svc/velocity
        ports:
        - containerPort: 25565
