FROM ubuntu

RUN apt-get update && apt-get install -y curl podman

RUN curl -sLo tar.gz https://github.com/cnoe-io/idpbuilder/releases/download/v0.10.2/idpbuilder-linux-amd64.tar.gz

RUN tar -xzf tar.gz && mv idpbuilder /usr/local/bin/idpbuilder && rm tar.gz